### ISSUE TITLE
Book of Skyearth I gives an unhandled error 

### ISSUE THREAD

**Issue by Sabbath93** [VarsityPhysicist/FFXIVRelicTrackerBlazor#1]
In ARR Animus tab when you change the book to Skyearth I it just tells you an unhandled error has occured

**Comment by VarsityPhysicist** [comment]
Thanks! I am able to reproduce this on my phone and will work on resolving this when I get out of work

**Comment by VarsityPhysicist** [comment]
I just pushed an update fixing this, thank you for reporting it!
It was a simple fix but it was causing all the book objectives to be off by 1 (skyfire I listed skyfire II objectives, skyfire II listed netherfire I objectives) and no one else had reported the issue...

**Comment by Sabbath93** [comment]
Glad I could help out! I'll be sure to post if I find any other issues too
