### ISSUE TITLE
Heavensward: Reconditioned Step Update

### ISSUE THREAD

**Issue by TakaMarth** [VarsityPhysicist/FFXIVRelicTrackerBlazor#3]
Heavensward: Reconditioned Step was updated to only require 180 Treated Crystal Sand, with the 3-6 sand bonus happening after the 90th Crystal Sand. Therefore, only 45-60 of each Crystal Sand and Umbrite should be required to complete the step now.

**Comment by VarsityPhysicist** [comment]
Thank you!
I've updated this just now. I think the calculations are correct, but I originally wrote them in a dumb way. But it looked correct with a bit of testing

**Comment by TakaMarth** [comment]
Thanks for fixing it so quickly! If you can also update the info on the website, it still says that 240 and 60-80 are needed in the description of the step on the website.

**Comment by VarsityPhysicist** [comment]
Ah, I was focused on the calculations and missed that.
Should be fixed now
